config/routes.rb
Rails.application.routes.draw do

#  get 'users/show'

  devise_for :users
  resources :users, only: [:show]

  resources :topics do
  	resources :bookmarks, except: [:index] do
 	 resources :likes, only: [:create, :destroy]
    end
  end
  
  resources :users, only: [:show]

  root to: 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title

  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def liked(post)
    likes.find_by(bookmark_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(current_user)
    topics_path(current_user)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  include Pundit

  before_action :authenticate_user!

  def new
    @bookmark = Bookmark.new
  end

  def create
    @user = current_user
    @topic = @user.topics.find(params[:topic_id])
    @url = bookmark_params[:url]
    bookmark = @topic.bookmarks.build(url: @url, user: @user)
    authorize bookmark

    bookmark.save
    redirect_to topics_path(current_user)
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmarks = Bookmark.all
    @topic = @bookmark.topic
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      redirect_to topics_path(current_user), notice: 'Bookmark was deleted'
    else
      flash[:error] = 'There was an error deleting the topic. Please try again.'
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.find(params[:id])
    authorize @bookmark

    @bookmark.update_attributes(bookmark_params)
    redirect_to topics_path, notice: 'Bookmark was updated'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    user = User.find_by(email: params[:sender])
    subject = params[:subject]
    content = params[:'body-plain']

    topic = user.topics.find_or_create_by(title: subject)

    bookmark = topic.bookmarks.build(topic: topic, url: content)

    head 200 if bookmark.save
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include Pundit

  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    if like.save
      flash[:notice] = 'Bookmark was liked.'
      redirect_to topics_path(current_user)
    else
      flash[:error] = 'There was an error saving the like. Please try again.'
    end
  end

  def destroy
    like = current_user.likes.find(params[:id])
    if like.destroy
      redirect_to topics_path(current_user)
    else
      flash[:error] = 'There was an error liking the bookmark. Please try again.'
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include Pundit

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.friendly.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = current_user
    @topic = current_user.topics.build(topics_params)
    @topic.user = @user

    if @topic.save
      flash[:notice] = 'Topic was created.'
      redirect_to topics_path(current_user)
    else
      flash[:error] = 'There was an error saving the topic. Please try again.'
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])

    if @topic.destroy
      flash[:notice] = 'Topic was deleted.'
      redirect_to topics_path(current_user)
    else
      flash[:error] = 'There was an error deleting the topic. Please try again.'
    end
  end

  private

  def topics_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pundit

  def show
    user = current_user
    @user_bookmarks = user.topics.all
    @liked_bookmarks = user.likes
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmarks.html.haml
%ul
  - topic.bookmarks.each do |bookmark|
    %li
      %b= link_to bookmark.url, bookmark.url
      = render partial: 'bookmarks/preview', locals: {url: bookmark.url}
    - if policy(bookmark).destroy?
      %p
        = link_to "Delete", topic_bookmark_path(topic, bookmark), method: :delete, data: {confirm: 'Are you sure you want to delete bookmark?'}
    - if policy(bookmark).update?
      | #{link_to "Edit", edit_topic_bookmark_path(topic, bookmark)}
    = render partial: 'likes/like', locals: {topic: topic, bookmark: bookmark }
    %div
      %br

app/views/bookmarks/_form.html.haml
= form_for [@topic, Bookmark.new] do |f|
  .row
    .col-md-8
      %b= f.text_field :url, :size => '25%', placeholder: "  Enter the new bookmark here"
    %br
      %br
        .col-md-8
          %b= f.submit 'Add', class: 'btn btn-success'

app/views/bookmarks/_preview.html.haml
.container
.media
.media-body
%a.embedly-card{:href => url} 
%script{:async => "", :charset => "UTF-8", :src => "//cdn.embedly.com/widgets/platform.js"}

app/views/bookmarks/edit.html.haml
= form_for [@topic, @bookmark] do |f|
  .container
    .row
      %h3 Edit the bookmark url:
      %br
        .col-md-8
          %b= f.text_field :url, :size => '25%', placeholder: "  Enter the new bookmark here"
        %br
          %br
            .col-md-8
              %b= f.submit 'Update', class: 'btn btn-success'

app/views/bookmarks/new.html.haml
= form_for [@topic, @bookmark] do |f|
  .container
    .row
      %h3 Add new bookmark url:
      %br
        .col-md-8
          %b= f.text_field :url, :size => '25%', placeholder: "  Enter the new bookmark here"
        %br
          %br
            .col-md-8
              %b= f.submit 'Create', class: 'btn btn-success'

app/views/bookmarks/show.html.haml
%h4= @bookmark.url
= link_to "New Bookmark", new_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success'
= link_to "Delete", [@topic, @bookmark], method: :delete, class: 'btn btn-danger', data: {confirm: 'you sure playa?'}
= link_to "Edit", edit_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success'
= render partial: 'likes/like', locals: { bookmark: @bookmark }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocmarks
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to 'Blocmarks', root_path
        %li= link_to 'All bookmarks', topics_path(current_user)
        - if current_user
          %li= link_to 'My bookmarks', user_path(current_user)
        .pull-right.user-info
          - if current_user
            Hello #{current_user.email}! #{link_to 'Sign out', destroy_user_session_path, method: :delete}
          - else
            = link_to 'Sign In', new_user_session_path
            or
            \#{link_to 'Sign Up', new_user_registration_path}
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:error]
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:alert]
      - elsif flash[:success]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:success]
    = yield

app/views/likes/_like.html.haml
- if policy(Like.new(bookmark: bookmark)).create?
  %div
    - if like2 = current_user.liked(bookmark)
      = link_to [topic, bookmark, like2], class: 'btn btn-danger', method: :delete do
        %i.glyphicon.glyphicon-star-empty> Unlike
    - else
      = link_to [topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do
        %i.glyphicon.glyphicon-star> Like

app/views/topics/_form.html.haml
= form_for [@user, Topic.new] do |f|
  .row
    .col-md-8
      %b= f.text_field :title, :size => '25%', placeholder: "  Enter the new topic here"
    %br
      %br
        .col-md-8
          %b= f.submit 'Add', class: 'btn btn-success'

app/views/topics/index.html.haml
.container
  %h2 Topics
  - @topics.each do |topic|
    .media
      .media-body
        - if current_user
          %h4
            %b= link_to topic.title, [topic]
        - else
          %h4
            %b= topic.title
        - if policy(topic).destroy?
          %p= link_to "Delete", [topic], method: :delete
        = render partial: 'bookmarks/bookmarks', locals: {topic: topic}
  - if current_user
    %div
      %br
        %br
          %b Add new topic
          = render partial: 'topics/form', locals: {user: @user, topic: @topic}

app/views/topics/show.html.haml
.container
  %h3= @topic.title
  .media
    .media-body
      = render partial: 'bookmarks/bookmarks', locals: {topic: @topic}
      %div
        - if policy(@topic).create?
          %b Add new bookmark
          = render partial: 'bookmarks/form', locals: {topic: @topic}
        %br
          %br

app/views/users/show.html.haml
.container
  %h3 My Bookmarks
  - @user_bookmarks.each do |topic|
    %h4= topic.title
    .media
      = render partial: 'bookmarks/bookmarks', locals: {topic: topic}
  %h3 Bookmarks I've liked
  - @liked_bookmarks.each do |bklike|
    .media
      .media-body
        %h4= bklike.bookmark.topic.title
        %h4
          %b= link_to bklike.bookmark.url, bklike.bookmark.url
          = render partial: 'bookmarks/preview', locals: {url: bklike.bookmark.url}
        = render partial: 'likes/like', locals: {topic: bklike.bookmark.topic, bookmark: bklike.bookmark  }

app/views/welcome/index.html.haml
.container
  .jumbotron
    %h1 Blocmarks
  %h3 Welcome to Blocmarks
  %p Blocmarks is a production quality social bookmarking app that allows users to email, manage and share bookmarked URLs. Please sign-up or sign-in to start blocmarking your favourite sites.